-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.alert_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid,
  disaster_id uuid,
  prediction_id uuid,
  channel text NOT NULL,
  recipient text NOT NULL,
  recipient_role text,
  subject text,
  body text,
  severity text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  external_ref text,
  error_message text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT alert_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT alert_notifications_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.ingested_events(id),
  CONSTRAINT alert_notifications_disaster_id_fkey FOREIGN KEY (disaster_id) REFERENCES public.disasters(id),
  CONSTRAINT alert_notifications_prediction_id_fkey FOREIGN KEY (prediction_id) REFERENCES public.predictions(id)
);
CREATE TABLE public.allocation_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  disaster_id uuid,
  zone_id uuid,
  location_id uuid,
  resource_id uuid,
  resource_type text,
  quantity double precision DEFAULT 0,
  median_quantity double precision DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT allocation_log_pkey PRIMARY KEY (id),
  CONSTRAINT allocation_log_disaster_id_fkey FOREIGN KEY (disaster_id) REFERENCES public.disasters(id),
  CONSTRAINT allocation_log_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.anomaly_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  anomaly_type text NOT NULL,
  severity text NOT NULL DEFAULT 'medium'::text,
  title text NOT NULL,
  description text,
  ai_explanation text,
  metric_name text NOT NULL,
  metric_value double precision NOT NULL,
  expected_range jsonb DEFAULT '{}'::jsonb,
  anomaly_score double precision,
  related_disaster_id uuid,
  related_location_id uuid,
  context_data jsonb DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'active'::text,
  acknowledged_by uuid,
  acknowledged_at timestamp with time zone,
  detected_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT anomaly_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT anomaly_alerts_related_disaster_id_fkey FOREIGN KEY (related_disaster_id) REFERENCES public.disasters(id),
  CONSTRAINT anomaly_alerts_related_location_id_fkey FOREIGN KEY (related_location_id) REFERENCES public.locations(id),
  CONSTRAINT anomaly_alerts_acknowledged_by_fkey FOREIGN KEY (acknowledged_by) REFERENCES public.users(id)
);
CREATE TABLE public.causal_audit_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  disaster_id uuid,
  report_url text,
  generated_at timestamp with time zone DEFAULT now(),
  status text DEFAULT 'generated'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT causal_audit_reports_pkey PRIMARY KEY (id),
  CONSTRAINT causal_audit_reports_disaster_id_fkey FOREIGN KEY (disaster_id) REFERENCES public.disasters(id)
);
CREATE TABLE public.disaster_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  disaster_id uuid,
  user_id uuid NOT NULL,
  user_name text,
  user_role text,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT disaster_messages_pkey PRIMARY KEY (id),
  CONSTRAINT disaster_messages_disaster_id_fkey FOREIGN KEY (disaster_id) REFERENCES public.disasters(id)
);
CREATE TABLE public.disastergpt_action_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id character varying,
  user_id character varying NOT NULL,
  action_type character varying NOT NULL,
  action_payload jsonb NOT NULL,
  result_status character varying CHECK (result_status::text = ANY (ARRAY['success'::character varying, 'failed'::character varying, 'pending'::character varying]::text[])),
  result_data jsonb,
  executed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT disastergpt_action_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.disastergpt_alert_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id character varying NOT NULL UNIQUE,
  alert_types ARRAY DEFAULT ARRAY['critical'::text, 'high'::text],
  enabled boolean DEFAULT true,
  last_notified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT disastergpt_alert_subscriptions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.disastergpt_digest_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id character varying NOT NULL,
  digest_content text NOT NULL,
  sent_at timestamp with time zone DEFAULT now(),
  CONSTRAINT disastergpt_digest_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.disastergpt_digest_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id character varying NOT NULL UNIQUE,
  user_role character varying,
  digest_time time without time zone DEFAULT '08:00:00'::time without time zone,
  timezone character varying DEFAULT 'UTC'::character varying,
  enabled boolean DEFAULT true,
  last_sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT disastergpt_digest_subscriptions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.disastergpt_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id character varying NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['user'::character varying, 'assistant'::character varying, 'system'::character varying]::text[])),
  content text NOT NULL,
  intent character varying,
  context_data jsonb,
  follow_up_suggestions jsonb,
  action_cards jsonb,
  tokens_used integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT disastergpt_messages_pkey PRIMARY KEY (id),
  CONSTRAINT disastergpt_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.disastergpt_sessions(session_id)
);
CREATE TABLE public.disastergpt_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id character varying NOT NULL UNIQUE,
  user_id character varying NOT NULL,
  user_role character varying,
  user_name character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_message_at timestamp with time zone DEFAULT now(),
  message_count integer DEFAULT 0,
  conversation_summary text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT disastergpt_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.disasters (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  type USER-DEFINED NOT NULL,
  severity USER-DEFINED NOT NULL,
  status USER-DEFINED DEFAULT 'active'::disaster_status,
  title character varying NOT NULL,
  description text,
  location_id uuid NOT NULL,
  affected_population integer,
  casualties integer,
  estimated_damage numeric,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone,
  metadata jsonb,
  location_name character varying,
  CONSTRAINT disasters_pkey PRIMARY KEY (id),
  CONSTRAINT disasters_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.donations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  disaster_id uuid,
  amount numeric DEFAULT 0,
  currency character varying DEFAULT 'USD'::character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['completed'::character varying, 'pending'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  payment_ref character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  request_id uuid,
  donation_type character varying DEFAULT 'money'::character varying,
  resource_items jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT donations_pkey PRIMARY KEY (id),
  CONSTRAINT donations_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.resource_requests(id),
  CONSTRAINT donations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT donations_disaster_id_fkey FOREIGN KEY (disaster_id) REFERENCES public.disasters(id)
);
CREATE TABLE public.donor_details (
  id uuid NOT NULL,
  donor_type text CHECK (donor_type = ANY (ARRAY['individual'::text, 'corporate'::text, 'foundation'::text, 'government'::text])),
  preferred_causes ARRAY,
  total_donated numeric DEFAULT 0,
  tax_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  verification_status character varying DEFAULT 'pending'::character varying CHECK (verification_status::text = ANY (ARRAY['pending'::character varying, 'verified'::character varying, 'rejected'::character varying, 'approved'::character varying]::text[])),
  CONSTRAINT donor_details_pkey PRIMARY KEY (id),
  CONSTRAINT donor_details_id_fkey FOREIGN KEY (id) REFERENCES public.users(id)
);
CREATE TABLE public.donor_pledges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  donor_id uuid NOT NULL,
  disaster_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  sourcing_request_id uuid,
  quantity_pledged integer DEFAULT 0,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'shipped'::text, 'received'::text, 'cancelled'::text])),
  user_id uuid,
  CONSTRAINT donor_pledges_pkey PRIMARY KEY (id),
  CONSTRAINT donor_pledges_user_id_fkey FOREIGN KEY (donor_id) REFERENCES public.users(id),
  CONSTRAINT donor_pledges_disaster_id_fkey FOREIGN KEY (disaster_id) REFERENCES public.disasters(id),
  CONSTRAINT donor_pledges_sourcing_request_id_fkey FOREIGN KEY (sourcing_request_id) REFERENCES public.resource_sourcing_requests(id)
);
CREATE TABLE public.event_store (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  event_type text NOT NULL,
  actor_id text,
  actor_role text,
  data jsonb DEFAULT '{}'::jsonb,
  old_state jsonb DEFAULT '{}'::jsonb,
  new_state jsonb DEFAULT '{}'::jsonb,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  version integer DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT event_store_pkey PRIMARY KEY (id)
);
CREATE TABLE public.external_data_sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_name text NOT NULL UNIQUE,
  source_type text NOT NULL,
  base_url text NOT NULL,
  poll_interval_s integer NOT NULL DEFAULT 900,
  is_active boolean NOT NULL DEFAULT true,
  last_polled_at timestamp with time zone,
  last_status text DEFAULT 'idle'::text,
  last_error text,
  config_json jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT external_data_sources_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fairness_audits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  disaster_id uuid,
  plan_index integer,
  applied_by uuid,
  applied_at timestamp with time zone DEFAULT now(),
  gini double precision,
  efficiency_score double precision,
  equity_score double precision,
  zone_allocations jsonb DEFAULT '{}'::jsonb,
  adjustments_applied jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fairness_audits_pkey PRIMARY KEY (id),
  CONSTRAINT fairness_audits_disaster_id_fkey FOREIGN KEY (disaster_id) REFERENCES public.disasters(id),
  CONSTRAINT fairness_audits_applied_by_fkey FOREIGN KEY (applied_by) REFERENCES public.users(id)
);
CREATE TABLE public.hotspot_clusters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  boundary jsonb NOT NULL DEFAULT '{}'::jsonb,
  centroid_lat double precision NOT NULL DEFAULT 0,
  centroid_lon double precision NOT NULL DEFAULT 0,
  request_count integer NOT NULL DEFAULT 0,
  total_people integer NOT NULL DEFAULT 0,
  dominant_type text NOT NULL DEFAULT 'other'::text,
  avg_priority double precision NOT NULL DEFAULT 2,
  priority_label text NOT NULL DEFAULT 'medium'::text,
  status text NOT NULL DEFAULT 'active'::text,
  request_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  firestore_synced boolean NOT NULL DEFAULT false,
  firestore_doc_id text,
  detected_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hotspot_clusters_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ingested_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_id uuid NOT NULL,
  external_id text,
  event_type text NOT NULL,
  title text,
  description text,
  severity text,
  latitude double precision,
  longitude double precision,
  location_name text,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  ingested_at timestamp with time zone NOT NULL DEFAULT now(),
  processed boolean NOT NULL DEFAULT false,
  processed_at timestamp with time zone,
  disaster_id uuid,
  prediction_ids ARRAY DEFAULT '{}'::uuid[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ingested_events_pkey PRIMARY KEY (id),
  CONSTRAINT ingested_events_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.external_data_sources(id),
  CONSTRAINT ingested_events_disaster_id_fkey FOREIGN KEY (disaster_id) REFERENCES public.disasters(id)
);
CREATE TABLE public.locations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  name character varying NOT NULL,
  type USER-DEFINED NOT NULL,
  latitude numeric NOT NULL CHECK (latitude >= '-90'::integer::numeric AND latitude <= 90::numeric),
  longitude numeric NOT NULL CHECK (longitude >= '-180'::integer::numeric AND longitude <= 180::numeric),
  address text,
  city character varying NOT NULL,
  state character varying NOT NULL,
  country character varying NOT NULL,
  postal_code character varying,
  population integer,
  area_sq_km numeric,
  metadata jsonb,
  CONSTRAINT locations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mission_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mobilization_id uuid NOT NULL,
  task_description text NOT NULL,
  is_completed boolean DEFAULT false,
  completed_by uuid,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mission_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT mission_tasks_mobilization_id_fkey FOREIGN KEY (mobilization_id) REFERENCES public.ngo_mobilization(id),
  CONSTRAINT mission_tasks_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES public.users(id)
);
CREATE TABLE public.model_evaluation_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_date date NOT NULL,
  report_period text NOT NULL DEFAULT 'weekly'::text,
  model_type text NOT NULL,
  model_version text,
  total_predictions integer DEFAULT 0,
  total_with_outcomes integer DEFAULT 0,
  accuracy double precision,
  mae double precision,
  rmse double precision,
  mape double precision,
  r_squared double precision,
  metrics_breakdown jsonb DEFAULT '{}'::jsonb,
  recommendations jsonb DEFAULT '[]'::jsonb,
  retrain_triggered boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT model_evaluation_reports_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ngo_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ngo_id uuid NOT NULL,
  cluster_id text,
  hotspot_id text,
  alert_type text NOT NULL DEFAULT 'hotspot_alert'::text,
  title text,
  message text,
  severity text DEFAULT 'medium'::text,
  latitude double precision,
  longitude double precision,
  centroid text,
  dominant_type text,
  request_count integer,
  total_people integer,
  avg_priority double precision,
  priority_label text,
  status text DEFAULT 'active'::text,
  distance_km double precision,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ngo_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT ngo_alerts_ngo_id_fkey FOREIGN KEY (ngo_id) REFERENCES public.users(id)
);
CREATE TABLE public.ngo_details (
  id uuid NOT NULL,
  organization_name text NOT NULL,
  registration_number text,
  operating_sectors ARRAY,
  website text,
  verification_status text DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text, 'approved'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  phone_number text,
  address text,
  latitude double precision,
  longitude double precision,
  CONSTRAINT ngo_details_pkey PRIMARY KEY (id),
  CONSTRAINT ngo_details_id_fkey FOREIGN KEY (id) REFERENCES public.users(id)
);
CREATE TABLE public.ngo_mobilization (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ngo_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  location_id uuid,
  required_volunteers integer DEFAULT 1,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'filled'::text, 'completed'::text, 'cancelled'::text])),
  created_at timestamp with time zone DEFAULT now(),
  target_request_ids ARRAY DEFAULT '{}'::uuid[],
  priority_score integer DEFAULT 0,
  CONSTRAINT ngo_mobilization_pkey PRIMARY KEY (id),
  CONSTRAINT ngo_mobilization_ngo_id_fkey FOREIGN KEY (ngo_id) REFERENCES public.users(id),
  CONSTRAINT ngo_mobilization_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.nl_query_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  session_id text,
  query_text text NOT NULL,
  query_type text,
  tools_called jsonb DEFAULT '[]'::jsonb,
  sql_generated text,
  response_text text,
  response_data jsonb DEFAULT '{}'::jsonb,
  model_used text DEFAULT 'claude-sonnet'::text,
  tokens_used integer,
  latency_ms integer,
  feedback_rating integer CHECK (feedback_rating >= 1 AND feedback_rating <= 5),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT nl_query_log_pkey PRIMARY KEY (id),
  CONSTRAINT nl_query_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.nlp_training_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid,
  corrected_by uuid,
  corrected_resource_type text,
  corrected_priority text,
  corrected_quantity integer,
  override_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT nlp_training_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT nlp_training_feedback_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.resource_requests(id),
  CONSTRAINT nlp_training_feedback_corrected_by_fkey FOREIGN KEY (corrected_by) REFERENCES auth.users(id)
);
CREATE TABLE public.notification_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  email boolean DEFAULT true,
  push boolean DEFAULT true,
  sms boolean DEFAULT false,
  in_app boolean DEFAULT true,
  critical_only boolean DEFAULT false,
  quiet_hours_start time without time zone,
  quiet_hours_end time without time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])) NOT VALI),
  read boolean DEFAULT false,
  read_at timestamp with time zone,
  action_url text,
  data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.operational_pulse (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_id uuid,
  target_id uuid,
  action_type text NOT NULL,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT operational_pulse_pkey PRIMARY KEY (id),
  CONSTRAINT operational_pulse_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id)
);
CREATE TABLE public.outcome_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  disaster_id uuid NOT NULL,
  prediction_id uuid,
  prediction_type text NOT NULL,
  predicted_severity text,
  predicted_casualties integer,
  predicted_damage_usd double precision,
  predicted_area_km2 double precision,
  actual_severity text,
  actual_casualties integer,
  actual_damage_usd double precision,
  actual_area_km2 double precision,
  severity_match boolean,
  casualty_error double precision,
  casualty_error_pct double precision,
  damage_error double precision,
  damage_error_pct double precision,
  area_error double precision,
  area_error_pct double precision,
  model_version text,
  logged_by text DEFAULT 'system'::text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT outcome_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT outcome_tracking_disaster_id_fkey FOREIGN KEY (disaster_id) REFERENCES public.disasters(id),
  CONSTRAINT outcome_tracking_prediction_id_fkey FOREIGN KEY (prediction_id) REFERENCES public.predictions(id)
);
CREATE TABLE public.platform_settings (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  platform_name character varying DEFAULT 'DisasterRM'::character varying,
  support_email character varying DEFAULT 'admin@disasterrm.org'::character varying,
  auto_sitrep boolean DEFAULT true,
  sitrep_interval integer DEFAULT 6,
  auto_allocate boolean DEFAULT true,
  ingestion_enabled boolean DEFAULT true,
  ingestion_interval integer DEFAULT 5,
  email_notifications boolean DEFAULT true,
  sms_alerts boolean DEFAULT false,
  maintenance_mode boolean DEFAULT false,
  api_rate_limit integer DEFAULT 100,
  max_upload_mb integer DEFAULT 10,
  session_timeout integer DEFAULT 60,
  data_retention_days integer DEFAULT 365,
  updated_at timestamp with time zone DEFAULT now(),
  approved_sla_hours double precision DEFAULT 2.0,
  assigned_sla_hours double precision DEFAULT 4.0,
  in_progress_sla_hours double precision DEFAULT 24.0,
  sla_enabled boolean DEFAULT true,
  CONSTRAINT platform_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.predictions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  disaster_id uuid,
  location_id uuid NOT NULL,
  model_version character varying NOT NULL,
  prediction_type USER-DEFINED NOT NULL,
  confidence_score numeric NOT NULL CHECK (confidence_score >= 0::numeric AND confidence_score <= 1::numeric),
  predicted_severity USER-DEFINED,
  predicted_start_date timestamp with time zone,
  predicted_end_date timestamp with time zone,
  affected_area_km numeric,
  predicted_casualties integer,
  features jsonb NOT NULL,
  metadata jsonb,
  CONSTRAINT predictions_pkey PRIMARY KEY (id),
  CONSTRAINT predictions_disaster_id_fkey FOREIGN KEY (disaster_id) REFERENCES public.disasters(id),
  CONSTRAINT predictions_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text,
  role text CHECK (role = ANY (ARRAY['victim'::text, 'ngo'::text, 'donor'::text, 'volunteer'::text, 'admin'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.request_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL,
  action text NOT NULL,
  actor_id uuid,
  actor_role text NOT NULL DEFAULT 'system'::text,
  old_status text,
  new_status text,
  details text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT request_audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.request_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL,
  volunteer_id uuid NOT NULL,
  field_notes text,
  photo_url text,
  verification_status text CHECK (verification_status = ANY (ARRAY['trusted'::text, 'dubious'::text, 'false_alarm'::text])),
  latitude_at_verification double precision,
  longitude_at_verification double precision,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT request_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT request_verifications_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.resource_requests(id),
  CONSTRAINT request_verifications_volunteer_id_fkey FOREIGN KEY (volunteer_id) REFERENCES public.users(id)
);
CREATE TABLE public.resource_consumption_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resource_type text NOT NULL,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  quantity_consumed double precision NOT NULL DEFAULT 0,
  quantity_available double precision NOT NULL DEFAULT 0,
  disaster_id uuid,
  location_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT resource_consumption_log_pkey PRIMARY KEY (id),
  CONSTRAINT resource_consumption_log_disaster_id_fkey FOREIGN KEY (disaster_id) REFERENCES public.disasters(id),
  CONSTRAINT resource_consumption_log_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.resource_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  victim_id uuid NOT NULL,
  resource_type text NOT NULL CHECK (resource_type = ANY (ARRAY['Food'::text, 'Water'::text, 'Medical'::text, 'Shelter'::text, 'Clothing'::text, 'Financial Aid'::text, 'Evacuation'::text, 'Volunteers'::text, 'Custom'::text, 'Multiple'::text])) NOT VALI),
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  description text,
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['critical'::text, 'high'::text, 'medium'::text, 'low'::text])) NOT VALI),
  latitude double precision,
  longitude double precision,
  address_text text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'availability_submitted'::text, 'under_review'::text, 'assigned'::text, 'in_progress'::text, 'delivered'::text, 'completed'::text, 'closed'::text, 'rejected'::text])),
  assigned_to uuid,
  assigned_role text CHECK (assigned_role IS NULL OR (assigned_role = ANY (ARRAY['ngo'::text, 'donor'::text, 'volunteer'::text]))) NOT VALI),
  estimated_delivery timestamp with time zone,
  attachments jsonb DEFAULT '[]'::jsonb,
  rejection_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  items jsonb DEFAULT '[]'::jsonb,
  nlp_classification jsonb,
  urgency_signals jsonb DEFAULT '[]'::jsonb,
  ai_confidence real,
  nlp_overridden boolean DEFAULT false,
  is_verified boolean DEFAULT false,
  verified_at timestamp with time zone,
  verified_by uuid,
  verification_status text CHECK (verification_status = ANY (ARRAY['trusted'::text, 'dubious'::text, 'false_alarm'::text])),
  nlp_priority text,
  nlp_confidence double precision,
  manual_priority text,
  extracted_needs jsonb,
  admin_note text,
  delivery_confirmation_code character varying,
  delivery_confirmed_at timestamp with time zone,
  fulfillment_entries jsonb DEFAULT '[]'::jsonb,
  fulfillment_pct integer DEFAULT 0,
  adopted_by uuid,
  adoption_status text,
  group_id uuid,
  head_count integer DEFAULT 1,
  linked_disaster_id uuid,
  disaster_distance_km double precision,
  disaster_id uuid,
  sla_escalated_at timestamp with time zone,
  sla_admin_alerted boolean DEFAULT false,
  sla_delivery_alerted boolean DEFAULT false,
  CONSTRAINT resource_requests_pkey PRIMARY KEY (id),
  CONSTRAINT resource_requests_victim_id_fkey FOREIGN KEY (victim_id) REFERENCES auth.users(id),
  CONSTRAINT resource_requests_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT resource_requests_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.resource_sourcing_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ngo_id uuid NOT NULL,
  resource_type text NOT NULL,
  quantity_needed integer NOT NULL,
  urgency text DEFAULT 'medium'::text CHECK (urgency = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  description text,
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'partially_funded'::text, 'filled'::text, 'closed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resource_sourcing_requests_pkey PRIMARY KEY (id),
  CONSTRAINT resource_sourcing_requests_ngo_id_fkey FOREIGN KEY (ngo_id) REFERENCES public.users(id)
);
CREATE TABLE public.resources (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  disaster_id uuid,
  location_id uuid NOT NULL,
  type USER-DEFINED NOT NULL,
  name character varying NOT NULL,
  quantity numeric NOT NULL,
  unit character varying NOT NULL,
  status USER-DEFINED DEFAULT 'available'::resource_status,
  allocated_to uuid,
  priority integer DEFAULT 5 CHECK (priority >= 1 AND priority <= 10),
  metadata jsonb,
  expiry_date timestamp with time zone,
  description text,
  provider_id uuid,
  priority_score integer DEFAULT 5,
  tags ARRAY DEFAULT '{}'::text[],
  quality_status character varying DEFAULT 'good'::character varying,
  latitude double precision,
  longitude double precision,
  CONSTRAINT resources_pkey PRIMARY KEY (id),
  CONSTRAINT resources_disaster_id_fkey FOREIGN KEY (disaster_id) REFERENCES public.disasters(id),
  CONSTRAINT resources_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT resources_allocated_to_fkey FOREIGN KEY (allocated_to) REFERENCES public.disasters(id),
  CONSTRAINT resources_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.users(id)
);
CREATE TABLE public.satellite_observations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source text NOT NULL DEFAULT 'firms'::text,
  external_id text,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  brightness double precision,
  frp double precision,
  confidence text,
  satellite text,
  instrument text,
  acq_datetime timestamp with time zone NOT NULL,
  daynight text,
  disaster_id uuid,
  raw_payload jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT satellite_observations_pkey PRIMARY KEY (id),
  CONSTRAINT satellite_observations_disaster_id_fkey FOREIGN KEY (disaster_id) REFERENCES public.disasters(id)
);
CREATE TABLE public.situation_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_date date NOT NULL,
  report_type text NOT NULL DEFAULT 'daily'::text,
  title text NOT NULL,
  markdown_body text NOT NULL,
  summary text,
  key_metrics jsonb DEFAULT '{}'::jsonb,
  recommendations jsonb DEFAULT '[]'::jsonb,
  model_used text DEFAULT 'claude-sonnet'::text,
  generated_by text DEFAULT 'system'::text,
  generation_time_ms integer,
  emailed_to ARRAY DEFAULT '{}'::text[],
  status text NOT NULL DEFAULT 'generated'::text,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT situation_reports_pkey PRIMARY KEY (id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.testimonials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  author_name character varying NOT NULL,
  author_role character varying,
  quote text NOT NULL,
  image_url text,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT testimonials_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email character varying NOT NULL UNIQUE,
  full_name character varying,
  phone character varying,
  organization character varying,
  metadata jsonb,
  is_profile_completed boolean DEFAULT false,
  role text DEFAULT 'victim'::text,
  verification_status character varying DEFAULT 'pending'::character varying,
  verification_notes text,
  additional_roles ARRAY DEFAULT '{}'::text[],
  trust_score integer DEFAULT 10,
  total_impact_points integer DEFAULT 0,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.victim_details (
  id uuid NOT NULL,
  current_status text CHECK (current_status = ANY (ARRAY['safe'::text, 'needs_help'::text, 'critical'::text, 'evacuated'::text])),
  needs ARRAY,
  location_lat double precision,
  location_long double precision,
  medical_needs text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  disaster_id uuid,
  CONSTRAINT victim_details_pkey PRIMARY KEY (id),
  CONSTRAINT victim_details_id_fkey FOREIGN KEY (id) REFERENCES public.users(id),
  CONSTRAINT victim_details_disaster_id_fkey FOREIGN KEY (disaster_id) REFERENCES public.disasters(id)
);
CREATE TABLE public.volunteer_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mobilization_id uuid NOT NULL,
  volunteer_id uuid NOT NULL,
  status text DEFAULT 'assigned'::text CHECK (status = ANY (ARRAY['assigned'::text, 'on_site'::text, 'completed'::text, 'withdrawn'::text])),
  assigned_at timestamp with time zone DEFAULT now(),
  feedback_notes text,
  completed_at timestamp with time zone,
  impact_score integer DEFAULT 1,
  CONSTRAINT volunteer_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT volunteer_assignments_mobilization_id_fkey FOREIGN KEY (mobilization_id) REFERENCES public.ngo_mobilization(id),
  CONSTRAINT volunteer_assignments_volunteer_id_fkey FOREIGN KEY (volunteer_id) REFERENCES public.users(id)
);
CREATE TABLE public.volunteer_certifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name character varying NOT NULL,
  issuer character varying DEFAULT 'Self-reported'::character varying,
  date_obtained date,
  expiry_date date,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'expired'::character varying, 'pending'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT volunteer_certifications_pkey PRIMARY KEY (id),
  CONSTRAINT volunteer_certifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.volunteer_details (
  id uuid NOT NULL,
  skills ARRAY,
  availability_status text DEFAULT 'available'::text,
  certifications ARRAY,
  deployed_location_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT volunteer_details_pkey PRIMARY KEY (id),
  CONSTRAINT volunteer_details_id_fkey FOREIGN KEY (id) REFERENCES public.users(id)
);
CREATE TABLE public.volunteer_ops (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  disaster_id uuid NOT NULL,
  task_description text NOT NULL DEFAULT ''::text,
  latitude double precision,
  longitude double precision,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  check_in_time timestamp with time zone NOT NULL DEFAULT now(),
  check_out_time timestamp with time zone,
  hours_worked numeric DEFAULT 0,
  notes text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT volunteer_ops_pkey PRIMARY KEY (id),
  CONSTRAINT volunteer_ops_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT volunteer_ops_disaster_id_fkey FOREIGN KEY (disaster_id) REFERENCES public.disasters(id)
);
CREATE TABLE public.volunteer_profiles (
  user_id uuid NOT NULL,
  skills ARRAY DEFAULT '{}'::text[],
  assets ARRAY DEFAULT '{}'::text[],
  availability_status text DEFAULT 'available'::text,
  bio text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT volunteer_profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT volunteer_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.weather_observations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  location_id uuid,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  temperature_c double precision,
  humidity_pct double precision,
  wind_speed_ms double precision,
  wind_deg double precision,
  pressure_hpa double precision,
  precipitation_mm double precision DEFAULT 0,
  visibility_m double precision,
  weather_main text,
  weather_desc text,
  observed_at timestamp with time zone NOT NULL,
  source text NOT NULL DEFAULT 'openweathermap'::text,
  raw_payload jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT weather_observations_pkey PRIMARY KEY (id),
  CONSTRAINT weather_observations_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);